name: CI/CD

on:
  push:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  backend-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Build Docker image
        run: docker build -t ggamnunq/busan .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ggamnunq/busan

      - name: Connect to EC2 & Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.WAS_SSH_PORT }}
          script: |
            cd /home/ubuntu/app
            docker-compose down
            docker rm -f redis || true
            docker rmi ggamnunq/busan || true
            docker image prune -f
            docker pull ggamnunq/busan
            docker-compose up -d